name: Only_tests_auto

on:
  # Триггеры: запуск при push в main ветку и при pull request
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Разрешение permissions для работы с репозиторием
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последний Ubuntu

    steps:
    # Шаг 1: Получение кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Установка Python
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Chrome
      run: sudo apt install google-chrome-stable

    # Шаг 3: Кэширование pip для ускорения сборок
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Шаг 4: Установка зависимостей
    - name: Install dependencies
      run: |
        source /home/runner/work/Only_Digital_test/Only_Digital_test/.venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt        

    # Шаг 5: Запуск тестов с pytest
    - name: Run tests
      run:  |
        pytest /home/runner/work/Only_Digital_test/Only_Digital_test/tests/footer_test.py -v

